Upstream, a test's tags are an array of strings now.
DreamItGetIT/statuscake pull request #20
Opened 2017-11-27 15:11 UTC by doertedev

Signed-off-by: Stefan Staudenmeyer <stefan.staudenmeyer@instana.com>

2017-11-29 12:17 UTC, croman commented
Can you add a documentation link for this change? @doertedev

2017-11-29 12:20 UTC, doertedev commented
https://www.statuscake.com/api/Tests/Get%20All%20Tests.md << see response example beneath.

2017-11-29 12:53 UTC, croman commented
From what I see, inserting / updating a test accepts a string field **TestTags**, but "Get all tests" returns a string array field called **Tags**. You are changing the **TestTags** type but I think you should add a **Tags** field instead.

2017-11-29 14:37 UTC, doertedev commented
I still don't really get some of your tests, but everything's green on my end now. Can you confirm?

2017-11-30 14:25 UTC, croman requested changes
Looks good, I think you need to delete "TestTags" usage when using the "Get All Tests" API, but then it's good to merge.

2017-11-30 14:25 UTC, croman commented on fixtures/tests_all_ok.json
> +      "TestTags": "tag1,tag2",
This is not needed, the "Get All Tests" doesn't return the "TestTags" field.

2017-11-30 14:25 UTC, croman commented on fixtures/tests_all_ok.json
> +      "TestTags": "tag3,tag4",
This is not needed, the "Get All Tests" doesn't return the "TestTags" field.

2017-11-30 14:25 UTC, croman commented on tests_test.go
> +		TestTags:    "tag1,tag2",
This is not needed, the "Get All Tests" doesn't return the "TestTags" field.

2017-11-30 14:25 UTC, croman commented on tests_test.go
> +		TestTags:    "tag3,tag4",
This is not needed, the "Get All Tests" doesn't return the "TestTags" field.

2018-07-28 15:29 UTC, closed without merging